language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ziskender/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ziskender/docker-react npm run test